### PR TITLE
Hook in CSV into main docs

### PR DESCRIPTION
**Pull request by rocky**
Here we have the CSV hooked into the main. See https://mathics-development-guide.readthedocs.io/en/add-csv/running.html#input-output-unicode-tables for how this looks on readthedocs.

As for going over the specific data, I've already gone over the Python dictionary mapping and I asume the CSV's were generated from that. 

As for the full list, this is just to tedious for me to do. I am happy to let whoever uses this to beta test it. And if no one does, then we saved tedious effort here :-)

I will note that some of this doesn't render quite as nice as it might using Sphinx's default CSV reader. Backslashes seem to disappear. 

And here are other warnings produced: 

```
github/Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Inline emphasis start-string without end-string.
Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Unexpected section title or transition.

||||||
Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Inline literal start-string without end-string.
Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Inline interpreted text or phrase reference start-string without end-string.
Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Inline emphasis start-string without end-string.
Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Unexpected section title or transition.

|||||||
Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Unexpected section title or transition.

||||
../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "<||".
../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "l||".
../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "l||||".
../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: ":-||".
../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "!||||".
../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "!||".
../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "r||".
../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "r||||".

```

### CODE REVIEW

**Comment by rocky** [comment]
@GarkGarcia if you are up for it, here are some things that I think would make the tables in the readthedocs slicker

* For each unicode symbol listed, make that linkable to a corresponding unicode URL
* For each WL named character listed, also make that linkable to the corresponding WL URL. 

Here is an example: 

| Unicode equivalent name      |Unicode |WL Unicode|WL named character        |
| -----------------------------| -------| -------- | ------------------------ | 
| MATHEMATICAL ITALIC CAPITAL D| [U+1D437](https://www.compart.com/en/unicode/U+1D437)  𝐷  | [U+0F74B](https://www.compart.com/en/unicode/U+0F48)   | [`\[CapitalDifferentialD]`](https://reference.wolfram.com/language/ref/CapitalDifferentialD.html) |

One way to do this would be to write a Python program that reads the CSV and outputs a [Sphinx table](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html).  This would be the thing that handles proper formatting of WL named characters and adds the links and so on.  By the way, in the above, I have added the rendering of the unicode symbols which does not appear in the various CSVs.

And such a Python program could be stored in the this repo so it can be run when there are updates.

**Comment by GarkGarcia** [comment]
> @GarkGarcia if you are up for it, here are some things that I think would make the tables in the readthedocs slicker
> 
>     * For each unicode symbol listed, make that linkable to a corresponding unicode URL
> 
>     * For each WL named character listed, also make that linkable to the corresponding WL URL.
> 
> 
> Here is an example:
> Unicode equivalent name 	Unicode 	WL Unicode 	WL named character
> MATHEMATICAL ITALIC CAPITAL D 	[U+1D437](https://www.compart.com/en/unicode/U+1D437) 𝐷 	[U+0F74B](https://www.compart.com/en/unicode/U+0F48)  	[`\[CapitalDifferentialD]`](https://reference.wolfram.com/language/ref/CapitalDifferentialD.html)
> 
> One way to do this would be to write a Python program that reads the CSV and outputs a [Sphinx table](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html). This would be the thing that handles proper formatting of WL named characters and adds the links and so on. By the way, in the above, I have added the rendering of the unicode symbols which does not appear in the various CSVs.
> 
> And such a Python program could be stored in the this repo so it can be run when there are updates.

Great idea, I'll work on it. I'm not sure if rendering the unicode symbols in the "WL Unicode" column is necessary thought. Could you give me an example on how to mark a single row of the table in RsT (with the links and everything)?

**Comment by GarkGarcia** [comment]
It looks like Sphinx can read CSV files and use them as tables: https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html#csv-files

@rocky This would probably be easier to maintain, but I think we should go with your idea because we could add the links you mentioned.

**Comment by GarkGarcia** [comment]
> It looks like Sphinx can read CSV files and use them as tables: https://sublime-and-sphinx-guide.readthedocs.io/en/latest/tables.html#csv-files
> 
> @rocky This would probably be easier to maintain, but I think we should go with your idea because we could add the links you mentioned.

Ohh, nevermind, just saw that you did this in the PR.

**Comment by GarkGarcia** [comment]
> And here are other warnings produced:
> 
> ```
> github/Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Inline emphasis start-string without end-string.
> Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Unexpected section title or transition.
> 
> ||||||
> Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Inline literal start-string without end-string.
> Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Inline interpreted text or phrase reference start-string without end-string.
> Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Inline emphasis start-string without end-string.
> Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Unexpected section title or transition.
> 
> |||||||
> Mathics3/mathics-development-guide/docs/translation-tables/full-unicode-conversion.rst:21: WARNING: Unexpected section title or transition.
> 
> ||||
> ../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "<||".
> ../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "l||".
> ../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "l||||".
> ../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: ":-||".
> ../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "!||||".
> ../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "!||".
> ../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "r||".
> ../resources/named-characters-data.csv:1: WARNING: Undefined substitution referenced: "r||||".
> ```

Yeah, the entries on the "ESC sequence alias" column are messed up because of quoting. I processed the tables using multiple Python scripts to get the final results, and I forgot to unquote the contents of the cells in some of them. This caused the scripts to quote certain characters multiple times.

**Review by GarkGarcia — APPROVED** [review]

**Comment by rocky** [comment]
> Great idea, I'll work on it. I'm not sure if rendering the unicode symbols in the "WL Unicode" column is necessary thought. Could you give me an example on how to mark a single row of the table in RsT (with the links and everything)?

Here is the header of the and the first row: 

```
.. list-table:: Title
   :widths: 40, 15, 15, 30
   :header-rows: 1


   * - Unicode equivalent name
     - Unicode
     - WL Unicode
     - WL named character
   * - MATHEMATICAL ITALIC CAPITAL D
     - `U+1D437 <https://www.compart.com/en/unicode/U+1D437>`_ 𝐷
     - `U+0F74B <https://www.compart.com/en/unicode/U+0F48>`_ ཈
     - `\[CapitalDifferentialD]  <https://reference.wolfram.com/language/ref/CapitalDifferentialD.html>`_
```

Really there's no magic here other than reading the link cited above on tables and knowing how to basically write the equivalent of `<a>` in RsT.

**Comment by GarkGarcia** [comment]
> > Great idea, I'll work on it. I'm not sure if rendering the unicode symbols in the "WL Unicode" column is necessary thought. Could you give me an example on how to mark a single row of the table in RsT (with the links and everything)?
> 
> Here is the header of the and the first row:
> 
> ```
> .. list-table:: Title
>    :widths: 40, 15, 15, 30
>    :header-rows: 1
> 
> 
>    * - Unicode equivalent name
>      - Unicode
>      - WL Unicode
>      - WL named character
>    * - MATHEMATICAL ITALIC CAPITAL D
>      - `U+1D437 <https://www.compart.com/en/unicode/U+1D437>`_ 𝐷
>      - `U+0F74B <https://www.compart.com/en/unicode/U+0F48>`_ ཈
>      - `\[CapitalDifferentialD]  <https://reference.wolfram.com/language/ref/CapitalDifferentialD.html>`_
> ```
> 
> Really there's no magic here other than reading the link cited above on tables and knowing how to basically write the equivalent of `<a>` in RsT.

Thanks! Final question: which columns do you want me to include in each table? I was thinking about including them all but it looks like you removed one column in your example

**Comment by rocky** [comment]
> Thanks! Final question: which columns do you want me to include in each table? I was thinking about including them all but it looks like you removed one column in your example

The below is from `Mathics3/mathics-development-guide/resources/unicode-to-wl-conversion.csv`

```
Unicode equivalent name,Unicode equivalent,WL named character (Unicode representation),WL named character
```

I see four columns. 

But when in doubt just include everything.

**Comment by GarkGarcia** [comment]
> > Thanks! Final question: which columns do you want me to include in each table? I was thinking about including them all but it looks like you removed one column in your example
> 
> The below is from `Mathics3/mathics-development-guide/resources/unicode-to-wl-conversion.csv`
> 
> ```
> Unicode equivalent name,Unicode equivalent,WL named character (Unicode representation),WL named character
> ```
> 
> I see four columns.
> 
> But when in doubt just include everything.

Ohh, you're right. My bad, I'll include all of the rows then.

**Comment by GarkGarcia** [comment]
@rocky Is there some sort of "include" directive in RST? And is there a way to escape strings so that they are RST-safe from Python?

**Comment by rocky** [comment]
> @rocky Is there some sort of "include" directive in RST? And is there a way to escape strings so that they are RST-safe from Python?

Don't know offhand. Did you try google?

**Comment by GarkGarcia** [comment]
Ok, the script for generating the tables is done. @rocky We should probably add `docs/translation-tables/*-table.rst` to `.gitignore` and make it so that readthedocs runs  `make` after each commit to `master`.

**Comment by GarkGarcia** [comment]
> > @rocky Is there some sort of "include" directive in RST? And is there a way to escape strings so that they are RST-safe from Python?
> 
> Don't know offhand. Did you try google?

I wasn't able to find anything on google at that time, but I found what I needed after more research. Sorry for that 😐️

**Comment by rocky** [comment]
> Ok, the script for generating the tables is done. @rocky We should probably add `docs/translation-tables/*-table.rst` to `.gitignore` and make it so that readthedocs runs `make` after each commit to `master`.

Should be done in 4ef2408

Look at https://mathics-development-guide.readthedocs.io/en/add-csv/running.html#input-output-unicode-tables for how this renders. 

BTW @GarkGarcia the tables look awesome! Great work!

**Comment by GarkGarcia** [comment]
> BTW @GarkGarcia the tables look awesome! Great work!

Thanks!

**Pull request merged**
